output: adding support for conditional output
If this is not changed, terraform will report this errors below:

Error: Error refreshing state: 7 error(s) occurred:

* module.spoke-1.module.dcos-infrastructure.module.dcos-bootstrap-instance.output.public_ip: At column 44, line 1: list \"module.dcos-bootstrap-instance.public_ips\" does not have any elements so cannot determine type. in:

${module.dcos-bootstrap-instance.public_ips[0]}
* module.vpc-peering.aws_route.this_routes_cross_region: aws_route.this_routes_cross_region: value of 'count' cannot be computed
* module.vpc-peering.aws_route.peer_routes_region: aws_route.peer_routes_region: value of 'count' cannot be computed
* module.vpc-peering.aws_route.this_routes_region: aws_route.this_routes_region: value of 'count' cannot be computed
* module.spoke-1.module.dcos-infrastructure.module.dcos-bootstrap-instance.output.private_ip: At column 45, line 1: list \"module.dcos-bootstrap-instance.private_ips\" does not have any elements so cannot determine type. in:

${module.dcos-bootstrap-instance.private_ips[0]}
* module.vpc-peering.aws_route.peer_routes_cross_region: aws_route.peer_routes_cross_region: value of 'count' cannot be computed
* module.spoke-1.module.dcos-infrastructure.module.dcos-bootstrap-instance.output.instance: At column 43, line 1: list \"module.dcos-bootstrap-instance.instances\" does not have any elements so cannot determine type. in:
${module.dcos-bootstrap-instance.instances[0]}
"